version: '3'

services:
  localhost:
    build:
      context: ./local_postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: 123456

  redis:
    restart: always
    image: redis:3.2-alpine
    ports:
      - "63799:6379"
